# Generated by Django 4.2.6 on 2023-10-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_plates', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delta_app.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delta_app.truck')),
            ],
        ),
    ]
